// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Slice for *About → `slice_zone`*
 */
export type AboutDocumentDataSliceZoneAboutContentSlice = prismic.Slice<
  "about_content",
  Record<string, never>,
  never
>;

type AboutDocumentDataSliceZoneSlice =
  AboutDocumentDataSliceZoneAboutContentSlice;

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * `slice_zone` field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slice_zone[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slice_zone: prismic.SliceZone<AboutDocumentDataSliceZoneSlice> /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AboutDocumentData>, "about", Lang>;

/**
 * Slice for *Careers → `slice_zone`*
 */
export type CareersDocumentDataSliceZoneJobListingSlice = prismic.Slice<
  "job_listing",
  Record<string, never>,
  never
>;

type CareersDocumentDataSliceZoneSlice =
  CareersDocumentDataSliceZoneJobListingSlice;

/**
 * Content for Careers documents
 */
interface CareersDocumentData {
  /**
   * `slice_zone` field in *Careers*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: careers.slice_zone[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slice_zone: prismic.SliceZone<CareersDocumentDataSliceZoneSlice> /**
   * Meta Title field in *Careers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: careers.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Careers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: careers.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Careers*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: careers.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Careers document from Prismic
 *
 * - **API ID**: `careers`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CareersDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CareersDocumentData>,
    "careers",
    Lang
  >;

/**
 * Item in *Company Settings → Social Links*
 */
export interface CompanySettingsDocumentDataSocialLinksItem {
  /**
   * Platform field in *Company Settings → Social Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: company_settings.social_links[].platform
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  platform: prismic.KeyTextField;

  /**
   * Link field in *Company Settings → Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: company_settings.social_links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Company Settings → Certifications*
 */
export interface CompanySettingsDocumentDataCertificationsItem {
  /**
   * Cert Name field in *Company Settings → Certifications*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: company_settings.certifications[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Cert Logo field in *Company Settings → Certifications*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: company_settings.certifications[].logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Cert Link field in *Company Settings → Certifications*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: company_settings.certifications[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Company Settings documents
 */
interface CompanySettingsDocumentData {
  /**
   * Company Name field in *Company Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: company_settings.company_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company_name: prismic.KeyTextField;

  /**
   * Logo field in *Company Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: company_settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Address field in *Company Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: company_settings.address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  address: prismic.KeyTextField;

  /**
   * Phone field in *Company Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: company_settings.phone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  phone: prismic.KeyTextField;

  /**
   * Email field in *Company Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: company_settings.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email: prismic.KeyTextField;

  /**
   * Social Links field in *Company Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: company_settings.social_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social_links: prismic.GroupField<
    Simplify<CompanySettingsDocumentDataSocialLinksItem>
  >;

  /**
   * Certifications field in *Company Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: company_settings.certifications[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  certifications: prismic.GroupField<
    Simplify<CompanySettingsDocumentDataCertificationsItem>
  >;
}

/**
 * Company Settings document from Prismic
 *
 * - **API ID**: `company_settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CompanySettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CompanySettingsDocumentData>,
    "company_settings",
    Lang
  >;

type ContactDocumentDataSliceZoneSlice = never;

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
  /**
   * `slice_zone` field in *Contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slice_zone[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slice_zone: prismic.SliceZone<ContactDocumentDataSliceZoneSlice> /**
   * Meta Title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

type FaqDocumentDataSliceZoneSlice = FaqSectionSlice;

/**
 * Content for FAQ documents
 */
interface FaqDocumentData {
  /**
   * Slice Zone field in *FAQ*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.slice_zone[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slice_zone: prismic.SliceZone<FaqDocumentDataSliceZoneSlice> /**
   * Meta Title field in *FAQ*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *FAQ*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *FAQ*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * FAQ document from Prismic
 *
 * - **API ID**: `faq`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FaqDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<FaqDocumentData>, "faq", Lang>;

type HomepageDocumentDataSliceZoneSlice =
  | HeroSlice
  | ServicesGridSlice
  | FaqSectionSlice
  | TestimonialsSlice
  | BlogOverviewSlice
  | CertificationsSlice
  | ContactFormSlice
  | StatsSlice
  | CtaSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * `slice_zone` field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slice_zone[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slice_zone: prismic.SliceZone<HomepageDocumentDataSliceZoneSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type IndustriesDocumentDataSliceZoneSlice = never;

/**
 * Content for Industries documents
 */
interface IndustriesDocumentData {
  /**
   * `slice_zone` field in *Industries*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: industries.slice_zone[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slice_zone: prismic.SliceZone<IndustriesDocumentDataSliceZoneSlice> /**
   * Meta Title field in *Industries*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: industries.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Industries*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: industries.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Industries*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: industries.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Industries document from Prismic
 *
 * - **API ID**: `industries`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IndustriesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<IndustriesDocumentData>,
    "industries",
    Lang
  >;

type PoliciesDocumentDataSliceZoneSlice = never;

/**
 * Content for Policies documents
 */
interface PoliciesDocumentData {
  /**
   * `slice_zone` field in *Policies*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: policies.slice_zone[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slice_zone: prismic.SliceZone<PoliciesDocumentDataSliceZoneSlice> /**
   * Meta Title field in *Policies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: policies.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Policies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: policies.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Policies*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: policies.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Policies document from Prismic
 *
 * - **API ID**: `policies`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PoliciesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PoliciesDocumentData>,
    "policies",
    Lang
  >;

/**
 * Slice for *Service → `slice_zone`*
 */
export type ServiceDocumentDataSliceZoneServiceDetailsSlice = prismic.Slice<
  "service_details",
  Record<string, never>,
  never
>;

type ServiceDocumentDataSliceZoneSlice =
  ServiceDocumentDataSliceZoneServiceDetailsSlice;

/**
 * Content for Service documents
 */
interface ServiceDocumentData {
  /**
   * Service Name field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * `slice_zone` field in *Service*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: service.slice_zone[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slice_zone: prismic.SliceZone<ServiceDocumentDataSliceZoneSlice> /**
   * Meta Title field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Service*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Service document from Prismic
 *
 * - **API ID**: `service`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ServiceDocumentData>,
    "service",
    Lang
  >;

type ServicesOverviewDocumentDataSliceZoneSlice = never;

/**
 * Content for Services Overview documents
 */
interface ServicesOverviewDocumentData {
  /**
   * `slice_zone` field in *Services Overview*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: services_overview.slice_zone[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slice_zone: prismic.SliceZone<ServicesOverviewDocumentDataSliceZoneSlice> /**
   * Meta Title field in *Services Overview*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_overview.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Services Overview*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_overview.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Services Overview*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services_overview.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Services Overview document from Prismic
 *
 * - **API ID**: `services_overview`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicesOverviewDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ServicesOverviewDocumentData>,
    "services_overview",
    Lang
  >;

export type AllDocumentTypes =
  | AboutDocument
  | CareersDocument
  | CompanySettingsDocument
  | ContactDocument
  | FaqDocument
  | HomepageDocument
  | IndustriesDocument
  | PoliciesDocument
  | ServiceDocument
  | ServicesOverviewDocument;

/**
 * Primary content in *BlogOverview → Default → Primary*
 */
export interface BlogOverviewSliceDefaultPrimary {
  /**
   * Heading field in *BlogOverview → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_overview.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Number of posts to show field in *BlogOverview → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_overview.default.primary.number_to_show
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  number_to_show: prismic.NumberField;
}

/**
 * Default variation for BlogOverview Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation for BlogOverview slice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogOverviewSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogOverviewSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogOverview*
 */
type BlogOverviewSliceVariation = BlogOverviewSliceDefault;

/**
 * BlogOverview Shared Slice
 *
 * - **API ID**: `blog_overview`
 * - **Description**: BlogOverview
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogOverviewSlice = prismic.SharedSlice<
  "blog_overview",
  BlogOverviewSliceVariation
>;

/**
 * Primary content in *Certifications → Items*
 */
export interface CertificationsSliceDefaultItem {
  /**
   * Certification Name field in *Certifications → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: certifications.items[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Certification Logo field in *Certifications → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: certifications.items[].logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Certification Link field in *Certifications → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: certifications.items[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for Certifications Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation for Certifications slice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CertificationsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<CertificationsSliceDefaultItem>
>;

/**
 * Slice variation for *Certifications*
 */
type CertificationsSliceVariation = CertificationsSliceDefault;

/**
 * Certifications Shared Slice
 *
 * - **API ID**: `certifications`
 * - **Description**: Certifications
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CertificationsSlice = prismic.SharedSlice<
  "certifications",
  CertificationsSliceVariation
>;

/**
 * Primary content in *ContactForm → Default → Primary*
 */
export interface ContactFormSliceDefaultPrimary {
  /**
   * Heading field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Subtext field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.subtext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtext: prismic.KeyTextField;
}

/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation for ContactForm slice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactFormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactForm*
 */
type ContactFormSliceVariation = ContactFormSliceDefault;

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: ContactForm
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactFormSlice = prismic.SharedSlice<
  "contact_form",
  ContactFormSliceVariation
>;

/**
 * Primary content in *Call To Action → Default → Primary*
 */
export interface CtaSliceDefaultPrimary {
  /**
   * Heading field in *Call To Action → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *Call To Action → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Button Label field in *Call To Action → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button Link field in *Call To Action → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Call To Action Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation for CTA
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Call To Action*
 */
type CtaSliceVariation = CtaSliceDefault;

/**
 * Call To Action Shared Slice
 *
 * - **API ID**: `cta`
 * - **Description**: A reusable CTA slice with heading, description, and button
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSlice = prismic.SharedSlice<"cta", CtaSliceVariation>;

/**
 * Primary content in *FaqSection → Default → Primary*
 */
export interface FaqSectionSliceDefaultPrimary {
  /**
   * Heading field in *FaqSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Frequently Asked Questions
   * - **API ID Path**: faq_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;
}

/**
 * Primary content in *FaqSection → Items*
 */
export interface FaqSectionSliceDefaultItem {
  /**
   * Question field in *FaqSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter a question here
   * - **API ID Path**: faq_section.items[].question
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *FaqSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.items[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Default variation for FaqSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation for FaqSection slice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSectionSliceDefaultPrimary>,
  Simplify<FaqSectionSliceDefaultItem>
>;

/**
 * Slice variation for *FaqSection*
 */
type FaqSectionSliceVariation = FaqSectionSliceDefault;

/**
 * FaqSection Shared Slice
 *
 * - **API ID**: `faq_section`
 * - **Description**: A section to display FAQs directly inside the slice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSectionSlice = prismic.SharedSlice<
  "faq_section",
  FaqSectionSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Background image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * CTA label field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_label: prismic.KeyTextField;

  /**
   * CTA link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation for Hero slice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Large hero with title, subtitle, background image and CTA
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Default variation for Navigation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NavigationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Navigation*
 */
type NavigationSliceVariation = NavigationSliceDefault;

/**
 * Navigation Shared Slice
 *
 * - **API ID**: `navigation`
 * - **Description**: Navigation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NavigationSlice = prismic.SharedSlice<
  "navigation",
  NavigationSliceVariation
>;

/**
 * Primary content in *ServicesGrid → Default → Primary*
 */
export interface ServicesGridSliceDefaultPrimary {
  /**
   * Heading field in *ServicesGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_grid.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;
}

/**
 * Primary content in *ServicesGrid → Items*
 */
export interface ServicesGridSliceDefaultItem {
  /**
   * Title field in *ServicesGrid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_grid.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Summary field in *ServicesGrid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_grid.items[].summary
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  summary: prismic.KeyTextField;

  /**
   * Link field in *ServicesGrid → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: services_grid.items[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for ServicesGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation for Services grid
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesGridSliceDefaultPrimary>,
  Simplify<ServicesGridSliceDefaultItem>
>;

/**
 * Slice variation for *ServicesGrid*
 */
type ServicesGridSliceVariation = ServicesGridSliceDefault;

/**
 * ServicesGrid Shared Slice
 *
 * - **API ID**: `services_grid`
 * - **Description**: Grid of services with title, summary and link
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesGridSlice = prismic.SharedSlice<
  "services_grid",
  ServicesGridSliceVariation
>;

/**
 * Primary content in *Stats → Default → Primary*
 */
export interface StatsSliceDefaultPrimary {
  /**
   * Intro text field in *Stats → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stats.default.primary.intro
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  intro: prismic.KeyTextField;
}

/**
 * Primary content in *Stats → Items*
 */
export interface StatsSliceDefaultItem {
  /**
   * Label (e.g., 250+ SO) field in *Stats → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stats.items[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Value field in *Stats → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stats.items[].value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  value: prismic.KeyTextField;
}

/**
 * Default variation for Stats Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default stats slice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StatsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StatsSliceDefaultPrimary>,
  Simplify<StatsSliceDefaultItem>
>;

/**
 * Slice variation for *Stats*
 */
type StatsSliceVariation = StatsSliceDefault;

/**
 * Stats Shared Slice
 *
 * - **API ID**: `stats`
 * - **Description**: Stats section with intro and multiple stat items
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StatsSlice = prismic.SharedSlice<"stats", StatsSliceVariation>;

/**
 * Primary content in *Testimonials → Items*
 */
export interface TestimonialsSliceDefaultItem {
  /**
   * Quote field in *Testimonials → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].quote
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  quote: prismic.RichTextField;

  /**
   * Author field in *Testimonials → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].author
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author: prismic.KeyTextField;

  /**
   * Company field in *Testimonials → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].company
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company: prismic.KeyTextField;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default testimonials slice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<TestimonialsSliceDefaultItem>
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials section with quotes, authors, and companies
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSliceZoneSlice,
      CareersDocument,
      CareersDocumentData,
      CareersDocumentDataSliceZoneSlice,
      CompanySettingsDocument,
      CompanySettingsDocumentData,
      CompanySettingsDocumentDataSocialLinksItem,
      CompanySettingsDocumentDataCertificationsItem,
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataSliceZoneSlice,
      FaqDocument,
      FaqDocumentData,
      FaqDocumentDataSliceZoneSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSliceZoneSlice,
      IndustriesDocument,
      IndustriesDocumentData,
      IndustriesDocumentDataSliceZoneSlice,
      PoliciesDocument,
      PoliciesDocumentData,
      PoliciesDocumentDataSliceZoneSlice,
      ServiceDocument,
      ServiceDocumentData,
      ServiceDocumentDataSliceZoneSlice,
      ServicesOverviewDocument,
      ServicesOverviewDocumentData,
      ServicesOverviewDocumentDataSliceZoneSlice,
      AllDocumentTypes,
      BlogOverviewSlice,
      BlogOverviewSliceDefaultPrimary,
      BlogOverviewSliceVariation,
      BlogOverviewSliceDefault,
      CertificationsSlice,
      CertificationsSliceDefaultItem,
      CertificationsSliceVariation,
      CertificationsSliceDefault,
      ContactFormSlice,
      ContactFormSliceDefaultPrimary,
      ContactFormSliceVariation,
      ContactFormSliceDefault,
      CtaSlice,
      CtaSliceDefaultPrimary,
      CtaSliceVariation,
      CtaSliceDefault,
      FaqSectionSlice,
      FaqSectionSliceDefaultPrimary,
      FaqSectionSliceDefaultItem,
      FaqSectionSliceVariation,
      FaqSectionSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      NavigationSlice,
      NavigationSliceVariation,
      NavigationSliceDefault,
      ServicesGridSlice,
      ServicesGridSliceDefaultPrimary,
      ServicesGridSliceDefaultItem,
      ServicesGridSliceVariation,
      ServicesGridSliceDefault,
      StatsSlice,
      StatsSliceDefaultPrimary,
      StatsSliceDefaultItem,
      StatsSliceVariation,
      StatsSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultItem,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
    };
  }
}
