// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_overview: dynamic(() => import("./BlogOverview")),
  certifications: dynamic(() => import("./Certifications")),
  contact_form: dynamic(() => import("./ContactForm")),
  cta: dynamic(() => import("./Cta")),
  faq_section: dynamic(() => import("./FaqSection")),
  hero: dynamic(() => import("./Hero")),
  navigation: dynamic(() => import("./Navigation")),
  services_grid: dynamic(() => import("./ServicesGrid")),
  stats: dynamic(() => import("./Stats")),
  testimonials: dynamic(() => import("./Testimonials")),
};
